이전 선형회귀에서 다항 회귀로 농어의 무게를 어느 정도 예측할 수 있지만, 여전히 훈련 세트보다 테스트 세트의 점수가 높은 것이 좀 찜찜하다.


이 문제를 해결하려면 제곱보다 더 고차항을 넣어야 하는데 얼마나 더 넣어야 하는 지 모르겠다. <br>
수동으로 일일이 넣기도 힘들다.

데이터의 종류가 길이뿐만이 아니라 두께 데이터도 있다면 어떨까? 

선형 회귀는 특성이 많을 수록 더 큰 효과를 낸다. 높이와 두께를 다항 회귀에 함께 적용시켜 보자.

### 다중 회귀

3-2까지는 하나의 특성을 사용하여 선형 회귀 모델을 훈련시켰다. 

여러 개의 특성을 사용한 선형 회귀를 ***다중 회귀*** 라고 한다.

2절에처럼 1개의 특성을 사용했을 때 선형 회귀 모델이 학습하는 것은 직선이다. <br>
2개의 특성을 사용하면 선형 회귀는 평면을 학습한다. 

그렇다면 3개 이상에서는 고차원을 그리거나 상상할 수 없다. 분명한 것은 <br>
선형 회귀를 단순한 직선이나 평면으로 생각하여 성능이 무조건 낮다고 오해해서는 안된다. 특성이 많은 고차원에서는 <br>
선형 회귀가 매우 복잡한 모델을 표현할 수 있다.

농어의 높이와 두께도 함께 사용해보겠다. 또한 이전 절에서처럼 3개의 특성을 각각 제곱하여 추가한다. <br>
거기다가 각 특성을 서로 곱해서 또다른 특성을 만들어 내겠다. 즉 농어 길이 X 농어 높이를 새로운 특성으로 만드는 것이다.

이렇게 기존의 특성을 사용해 새로운 특성을 뽑아내는 작업을 ***특성 공학***이라 한다.

우리가 직접 특성을 곱할 수도 있지만 사이킷런에서 사용하는 편리한 도구를 사용해 보자.

일단 농어 데이터를 다시 불러오는 것에서 시작해 보자. <br>


### 농어 데이터 준비 <br>
http://bit.ly/perch_csv_data <br>
http://bit.ly/perch_data

농어의 데이터 특성이 3개로 늘어났기 때문에 데이터를 복사해 넣는 것도 복잡하다. <br>
인터넷에서 데이터를 바로 다운로드하여 사용할 수는 없을까? <br>
판다스를 사용하면 바로 가능하다.

판다스는 유명한 데이터 분석 라이브러리이다. 데이터프레임은 판다스의 핵심 데이터 구조이다. <br>
넘파이 배열과 비슷하게 다차원 배열을 다룰 수 있지만 훨씬 더 많은 기능을 제공한다. <br>
또 데이터프레임은 넘파이 배열로 쉽게 바꿀 수 있다.

판다스 프레임을 만들기 위해 사용하는 팡리은 csv 파일이다. <br>
pandas의 read_csv 함수를 통해 데이터프레임을 만든 다음 to_numpy() 함수를 통해 넘파이 배열로 바꾼다.

In [1]:
import pandas as pd
df = pd.read_csv("http://bit.ly/perch_csv_data")
perch_full = df.to_numpy()
print(perch_full)

[[ 8.4   2.11  1.41]
 [13.7   3.53  2.  ]
 [15.    3.82  2.43]
 [16.2   4.59  2.63]
 [17.4   4.59  2.94]
 [18.    5.22  3.32]
 [18.7   5.2   3.12]
 [19.    5.64  3.05]
 [19.6   5.14  3.04]
 [20.    5.08  2.77]
 [21.    5.69  3.56]
 [21.    5.92  3.31]
 [21.    5.69  3.67]
 [21.3   6.38  3.53]
 [22.    6.11  3.41]
 [22.    5.64  3.52]
 [22.    6.11  3.52]
 [22.    5.88  3.52]
 [22.    5.52  4.  ]
 [22.5   5.86  3.62]
 [22.5   6.79  3.62]
 [22.7   5.95  3.63]
 [23.    5.22  3.63]
 [23.5   6.28  3.72]
 [24.    7.29  3.72]
 [24.    6.38  3.82]
 [24.6   6.73  4.17]
 [25.    6.44  3.68]
 [25.6   6.56  4.24]
 [26.5   7.17  4.14]
 [27.3   8.32  5.14]
 [27.5   7.17  4.34]
 [27.5   7.05  4.34]
 [27.5   7.28  4.57]
 [28.    7.82  4.2 ]
 [28.7   7.59  4.64]
 [30.    7.62  4.77]
 [32.8  10.03  6.02]
 [34.5  10.26  6.39]
 [35.   11.49  7.8 ]
 [36.5  10.88  6.86]
 [36.   10.61  6.74]
 [37.   10.84  6.26]
 [37.   10.57  6.37]
 [39.   11.14  7.49]
 [39.   11.14  6.  ]
 [39.   12.43  7.35]
 [40.   11.93

타깃 데이터는 이전과 동일한 방법으로 준비한다.

In [2]:
import numpy as np
perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])

그다음 perch_full과 perch_weight를 훈련 데이터와 테스트 데이터로 나눈다.

In [3]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(perch_full, perch_weight, random_state=42)

이 데이터를 활용해 새로운 특성을 만들겠다.

### 사이킷런의 변환기

사이킷런에서 특성을 만들거나 전처리하기 위해 제공하는 다양한 클래스를 <br>
***변환기***라고 한다.

변환기 클래스는 모두 fit(), transform() 메서드를 제공한다.

우리가 사용할 변환기는 PolynomialFeatures 클래스이다. <br>
이 클래스는 sklearn.preprocessing 패키지에 포함되어 있다.

In [4]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures()

<**예제**>
2개의 특성 2와 3으로 이루어진 샘플 하나를 적용하겠다. 앞서 이야기한 것처럼 이 클래스의 객체르 만든 다음 <br>
fit(), transform() 메서드를 차례대로 호출하겠다.

In [5]:
poly.fit([[2, 3]])
print(poly.transform([[2, 3]]))

[[1. 2. 3. 4. 6. 9.]]


fit() 메서드는 새롭게 만들 특성 조합을 찾고 <br>
transform() 메서드는 실제로 데이터를 변환한다.

변환기는 입력 데이터를 변환하는 데 타깃 데이터가 필요하지 않다. fit() 함수에 타깃 데이터 넣을 필요 없다.

PolynomialFeatures 클래스는 기본적으로 각 특성을 제곱한 항을 추가하고 특성끼리 서로 곱한 항을 추가한다.

예시를 보면 <br>
2와 3을 각기 제곱한 4와 9가 추가되었고, 2와 3을 곱한 6이 추가되었다. 1은 왜 추가되었을까?

무게 = a * 길이 + b * 높이 + c * 두께 + d * 1

사실 선형 방정식의 절편을 항상 값이 1인 특성과 곱해지는 계수라고 볼 수 있다. <br>
이렇게 놓고 보면 특성은 항상 ( 길이, 높이, 두께, 1 ) 이 된다.

하지만 사이킷런의 선형 모델은 자동으로 절편을 추가하므로 굳이 특성을 만들 필요가 없다. <br>
include_bias = False로 지정하여 다시 특성을 변환하겠다.

In [7]:
poly = PolynomialFeatures(include_bias = False)
poly.fit([[2,3]])
print(poly.transform([[2,3]]))

[[2. 3. 4. 6. 9.]]
